name: Mindcrack Marathon KotL
version: 1
description: King of the Ladder for the Mindcrack Marathon/
author: Matthew Salsamendi

main: com.mcprohosting.plugins.mindcrack.kotl.KotL
database: false
depend: [BoneSQLib]

commands:
   kotl:
     description: Managment commands for KotL
     permission: kotl
     usage: /<command>
   setspawn:
     description: Set one of the four spawn locations for the game to the current location of the player.
     usage: /<command> <spawn number>
   setladder:
     description: Set the position of the top of the ladder to the current location of the player.
     usage: /<command>
   top:
     descriptions: Find out who the top player is on the server.
     usage: /<command>
permissions:
   kotl.*:
     description: Gives access to all KotL commands
     children:
       kotl.reset: true
       kotl.changeblocks: true
   kotl.changeblocks:
     description: Allow player to break and place blocks
     default: op
   kotl.configure:
     description: Allow player to set the spawn and ladder locations
     default: op
   kotl.mindcrack:
     description: Allow player to stay in game if they day
     default: op